# LLM Configuration
llm:
  provider: anthropic  # or 'openai'
  model: claude-3-sonnet-20240229  # or 'gpt-3.5-turbo' for OpenAI
  temperature: 0.0
  api_key: ${ANTHROPIC_API_KEY}  # Use environment variable

# Embeddings Configuration
embeddings:
  provider: openai
  model: text-embedding-3-small
  api_key: ${OPENAI_API_KEY}

# Processing Configuration
processing:
  batch_size: 10
  max_retries: 3
  retry_delay: 1
  max_concurrency: 5

# Caching Configuration
caching:
  embeddings_cache_dir: ./cache/embeddings
  llm_cache_path: .langchain.db

# Output Configuration
output:
  graph_format: png
  export_format: json
  visualization:
    figure_size: [12, 8]
    node_size: 700
    node_color: lightblue
    edge_color: gray
    font_size: 10

# Taxonomy Configuration
taxonomy:
  min_confidence: 0.6
  max_tags: 100
  chunk_size: 1000
  chunk_overlap: 200 