# Markdown Tag Taxonomy Generator Configuration

# LLM settings
llm:
  provider: openai  # openai, anthropic, etc.
  api_key: "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"  # API key for the LLM provider
  model: gpt-4o  # model name
  temperature: 0.2  # randomness (0-1)
  max_tokens: 2000  # max tokens per response

# Document processing settings
document:
  chunk_size: 1000  # size of document chunks
  chunk_overlap: 200  # overlap between chunks
  exclude_patterns:  # glob patterns to exclude
    - "**/node_modules/**"
    - "**/.git/**"
  frontmatter: true  # extract frontmatter metadata
  parse_links: true  # extract and analyze links

# Tag extraction settings
tag_extraction:
  min_importance: 3  # minimum importance score (1-10)
  max_tags_per_document: 15  # max tags per document
  use_existing_tags: true  # use tags from frontmatter
  consolidate_similar: true  # merge similar tags

# Taxonomy settings
taxonomy:
  min_confidence: 0.6  # minimum relationship confidence (0-1)
  max_depth: 5  # maximum hierarchy depth
  visualization:
    format: png  # png, svg, html
    node_size: 700
    font_size: 10
    layout: hierarchical  # hierarchical, circular, force
  export_formats:
    - json
    - yaml
    - graphml

# Output settings
output:
  detailed_report: true  # generate detailed report
  tag_descriptions: true  # include tag descriptions
  include_sources: true  # link tags to source documents